### ISSUE TITLE
Do we need IPv4?

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#10]
We should discuss whether we need IPv4, and if so, how to provide it on the local network :)

>But then I am also mindful apps don't like IPv6 still, so... They kinda need the v4 nat
-- @benhylau 

>I almost just wanna run a yggdrasil ipv6 only network and let apps that don't support v6 fail catastrophically
-- @benhylau 

>I also like the idea of pushing to have the network be IPv6-only! Fun fact: T-Mobile's network infrastructure (including cellular) is IPv6 only and uses v4-in-v6 tunneling when needed.
-- @raylas

**Comment by RangerMauve** [comment]
I think some software isn't IPv6 ready, so it'd be nice to have.

**Comment by benhylau** [comment]
😃 we have IPv4
https://github.com/dweb-camp-2019/meshnet/blob/master/testnet/README.md

😢 we will never have IPv6
>I think some software isn't IPv6 ready, so it'd be nice to have.
