### ISSUE TITLE
Call for Network Stewards

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#21]
**Network Stewards** at DWeb Camp are people who are committed to helping other campers learn about and tinker with the local network and Internet connectivity arrangement, and to help people address general device connectivity issues should that arise around them during their stay at Camp. Here are the expectations:

- Have general familiarity with the local network infrastructure. This does not imply technical proficiency, but it means:
    - Have spent an hour looking through documentation on this repository and its [Issues board](https://github.com/dweb-camp-2019/meshnet/issues)
    - Have gone on a short 15 minute tour to physically locate the wireless mesh network nodes and where local services are provided, and can point these infrastructures out to other campers or lead such a 15 minute walk to onboard new Network Stewards
- Have joined this [Matrix chat room](https://riot.im/app/#/room/#dweb-camp-2019-mesh:matrix.org) so they can ping other Network Stewards during Camp as needed
- Wear signage to indicate they are here to help if people are struggling with network issues or would like to learn more
- Open to leading/helping activities relating to the network infrastructure at Camp

_Some but not all_ of the Network Stewards would have:

- Participated in the build events leading up to Camp
- Technical familiarity with the network topology
- Full admin access to the network infrastructure

We hope to have at least 12 Network Stewards during Camp days. Please post on this thread or say hi on the Matrix chat if you are interested to take part!

**Comment by tchoi8** [comment]
I'd like to sign up to be a network steward. I look forward to learning about the network topology and basic technical concepts and terms.  I'll join the chatroom soon.

**Comment by jonscol** [comment]
I’m interested in mesh networks. I want to create one for my acreage. I have some network knowledge.
