### ISSUE TITLE
Update espressobin documentations

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#32]

**Comment by llunaCreixent** [comment]
Notes taken during flash and installation precesses:
- espresobin/install reference is written to early in the documentation. It is confusing.
- Power off (both usb and power) before running install script.
- No SD card needed for the `setenv` script.

**Comment by benhylau** [comment]
Resolved in 0c4501a761664c0d1768076aeaca2d6c333924c5
