### ISSUE TITLE
Espressobin hospital

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#36]
Two used espressobins arrived dead, and one that we've been using seems to have a broken `wan` port. They are now labeled and this sheet tracks statuses at the mesh node hospital:

| Node | Description | Status |
|:------|:------------|:-------|
| P1 | Purchased used, never worked | Doesn't boot |
| P2 | Purchased used, never worked | Doesn't boot |
| P3 | Purchased new, probably worked before | `wan` port seems dead |

**Comment by llunaCreixent** [comment]
For P1, I tried...
- Manual flashing to latest u-boot
     - https://www.armbian.com/espressobin/
- The boot flash for our board is: flash-image-ddr3-1g-2cs-1000_800.bin
     - https://espressobin.net/forums/topic/mainline-linux-not-running-at-1ghz/
     - https://forum.armbian.com/topic/4089-espressobin-support-development-efforts/page/20/
     - https://forum.armbian.com/topic/10335-espressobin-update-to-585-results-in-kernel-panic/?tab=comments#comment-79916
- If I update the boot loader with USB key,
     - http://wiki.espressobin.net/tiki-index.php?page=Update+the+Bootloader
     - I get these ERRORS:
```
scanning bus 0 for devices... Device NOT ready
   Request Sense returned 02 3A 00
WARN halted endpoint, queueing URB anyway.
Unexpected XHCI event TRB, skipping... (3f79fcf0 00000000 13000000 01008401)
BUG: failure at drivers/usb/host/xhci-ring.c:489/abort_td()!
BUG!
resetting ...
```
- If I try to update the boot loader with TFTP server,
     - http://wiki.espressobin.net/tiki-index.php?page=Update+the+Bootloader#TFTP_server
     - I could not get an addr for the board

- Current STATE when I connect through console interface:
```
Connecting to /dev/ttyUSB0, speed 115200
 Escape character: Ctrl-\ (ASCII 28, FS): enabled
Type the escape character followed by C to get back,
or followed by ? to see other options.
----------------------------------------------------
 0
starting USB...
USB0:   Register 2000104 NbrPorts 2
Starting the controller
USB XHCI 1.00
USB1:   USB EHCI 1.00
scanning bus 0 for devices... 1 USB Device(s) found
scanning bus 1 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
/
** Bad device usb 0 **
## Executing script at 06d00000
Wrong image format for "source" command
/boot/
** Bad device usb 0 **
## Executing script at 06d00000
Wrong image format for "source" command
scanning bus for devices...
SATA link 0 timeout.
AHCI 0001.0300 32 slots 1 ports 6 Gbps 0x1 impl SATA mode
flags: ncq led only pmp fbss pio slum part sxs

Device 0: unknown device
/
** Bad device scsi 0 **
## Executing script at 06d00000
Wrong image format for "source" command
/boot/
** Bad device scsi 0 **
## Executing script at 06d00000
Wrong image format for "source" command
/
Card did not respond to voltage select!
mmc_init: -95, time 50
** Bad device mmc 1 **
## Executing script at 06d00000
Wrong image format for "source" command
/boot/
Card did not respond to voltage select!
mmc_init: -95, time 43
** Bad device mmc 1 **
## Executing script at 06d00000
Wrong image format for "source" command
/
sdhci_transfer_data: Error detected in status(0x108000)!
mmc_init: -110, time 5783
** Bad device mmc 0 **
## Executing script at 06d00000
Wrong image format for "source" command
/boot/
sdhci_transfer_data: Error detected in status(0x108000)!
mmc_init: -110, time 5453
** Bad device mmc 0 **
## Executing script at 06d00000
Wrong image format for "source" command
```

**Comment by llunaCreixent** [comment]
For P2,
- I do not get prompt when connecting through console interface.

**Comment by benhylau** [comment]
For P1, the micro-USB is physically half-broken. I have to physically hold it down to have it maintain a connection to debug. Occasionally it would boot into Debian but not fully. I think the SD card port is needs physical repair.

For P2, the device seems bricked but may be rescuable, and these resources may be useful as the symptoms look similar:
- https://forum.armbian.com/topic/8845-bricked-my-2g-espressobin-cannot-seem-to-recover-via-sata-or-uart/
- https://dl.armbian.com/espressobin/u-boot/rescue/uart-rescue-espressobin.pdf

For P3, it kinda just started working by itself again...

**Comment by benhylau** [comment]
P1 and P2 labeled defective for next year.
