### ISSUE TITLE
Network activities planning

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#38]
- [x] Draft _Starter Kit_ to set expectations (@GoodieHicks)
- [ ] Draft _Challenges_ based on our deployment experience (@GoodieHicks)
- [x] Map of physical locations to node-ids (@GoodieHicks)
- [x] ~~Print large maps~~ and make buttons (@GoodieHicks + @benhylau)
- [x] Start email thread with Network Stewards (@benhylau)
- [x] Ensure Network Stewards are in same Matrix chat (@benhylau)
- [x] Submit activities to SCHED (@benhylau)

**Comment by benhylau** [comment]
Based on yesterday's conversations, we will have the following nodes to start. It is likely that new nodes will get added and their node types could change during Build / Camp days, but this is what we currently have.

| Map ID | Map Name              | Mesh Node IP | Mesh Node Type |
|:-------|:----------------------|:-------------|:---------------|
| 2      | Camp Enoki            | 10.2.0.1     | relay          |
| 5      | Universal Access Hall | 10.5.0.1     | gateway        |
| 8      | Mesh Hall             | 10.8.0.1     | edge           |
| 11     | Medical               | 10.11.0.1    | relay          |
| 18     | Camp Lions Mane       | 10.18.0.1    | edge           |
| 19     | Powerhouse            | 10.19.0.1    | edge           |

* The Node IP addresses are currently randomly generated, but during Build Days we will change them to match the Map IDs.

**Comment by benhylau** [comment]
| Date   | Time        | Session                                                   |
|:-------|:------------|:----------------------------------------------------------|
| JUL 18 | 13:30-16:30 | Orientation: Get on the Mesh!                             |
| JUL 19 | 10:30-11:00 | Network Steward meet*                                     |
| JUL 19 | 11:00-13:00 | Why Community Networks?**                                 |
| JUL 19 | 13:00-15:00 | Lunch with Mesh Potatoes                                  |
| JUL 20 | 11:30-13:00 | The Value in Community Networks / Constructing Connection |
| JUL 20 | 13:00-15:00 | Lunch with Mesh Potatoes                                  |
| JUL 20 | 15:00-17:00 | Mesh Playground                                           |

_*Followed by 2 people shifts at Mesh Hall until 17:00_
_**Followed by Threads & Cups game_
_***Ad-hoc LibreRouter hands-on activities throughout the days_

**Comment by benhylau** [comment]
Copy for propaganda https://hackmd.io/mI678v-8TS6KRNiGSLCC_w?view

**Comment by nicopace** [comment]
I can do a cable building activity. it takes 90 minutes, and can be done for up to 20 people.
