### ISSUE TITLE
List of potentially useful hardware

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#4]
Tracking a list of hardware that may be useful for us. Please include the following details:

- Name: `device model`
- Description: `what is it and why it may be useful`
- Availability: `pricing information, where to get it, will you bring them?`

**Comment by benhylau** [comment]
## GLB1300
- Description: Default router for Althea's Babel + WireGuard, ~100 Mbps with WireGuard in use, not good for gigabit nodes but may be a good alternative to more expensive ClearFog Pro in some low traffic nodes
- Availability: [Althea ships them](https://althea-routers.myshopify.com/products/althea-glb1300) for USD 90 or Amazon

**Comment by benhylau** [comment]
## UCTRONICS PoE Splitter Gigabit 5V
- Less cabling when connecting Raspberry Pis and most other SBCs with PoE switch
- Many cheaper PoE splitters have voltage drop / quality control problems, this has excellent reviews
- 802.3af and gigabit support

Availability: USD 15 [from Amazon](https://www.amazon.com/UCTRONICS-PoE-Splitter-Gigabit-Raspberry/dp/B07CNKX14C/)

**Comment by benhylau** [comment]
**UCTRONICS PoE Splitter Gigabit 5V** works great, ordering a bunch, especially for @amark's fleet of Raspberry Pis. The SRW208P PoE switches will power these.

[NETGEAR GS305E](https://www.amazon.com/gp/product/B07PJ7XZ7X/ref=ox_sc_act_title_2?smid=ATVPDKIKX0DER&psc=1) for VLAN tagging the mesh links are being tested.

**Comment by nicopace** [comment]
I will be bringing three librerouter.org devices.
